# **CS825-001, Spring/Summer 2020**

## **Assignment 1 - Question 1**

### **Assigned Date: Saturday, May 16, 2020**

### **Due Date: Tuesday, May 28, 2020**


# **Question - 1**

### Write a program that reads a grayscale image in raw format from a file; resize the image to a specified resolution using the **single point resampling method**; and save the new image into a new file in raw format. Test your program with the following data

1. Input image filename: “**rose.raw**”
   *   Format: **grayscale**
   *   Original resolution: **256x256**
   *   New resolution: **500x500**


2. Input image filename: “**winter-landscape-1600x1000-grayscale.raw**”

    *  Format: **grayscale**
    *  Original resolution: **1600x1000**
    *  New resolution: **1000x625**


3. Input image filename: “**winter-landscape-1600x1000-grayscale.raw**”

    *  Format: **grayscale**
    *  Original resolution: **1600x1000**
    *  New resolution: **640x400**




---



# **Solution**

# **Input Functions**

Below are some of the functions that take the input from the user such as the resolution (rows, columns) and filename of the image.


### **Importing Libraries**

* The only reason that `numpy` library is used to convert the raw image into **array of pixels**. Mainly used to **store the values in an array**.

* The only reason that `more_itertools` is used because of its `numeric_range` function. A extension of the built-in `range()` function whose arguments can be any orderable numeric type. With only stop specified, start defaults to 0 and step defaults to 1. The output items will match the type of stop. To be more precise, this library helps the for loop to loop around decimal numbers.

In [0]:
# Necessary libraries used for this assignment
import numpy as np

### **Defining all the input functions**

In [0]:
# Function: Resolution
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the number of rows, columns of the old image and the new image.
#
#    Parameter:    None
#
#    Result:       returns the value of the inputted rows and columns of the old and new image.
#   
#    Author:       Tanu Nanda Prabhu

def resolution():

    # Explicitly typed-casted to intergers, because the rows and columns of the images must an integer. 
    ROWS = int(input("Enter the number of rows of the old image: "))
    COLS = int(input("Enter the number of columns of the old image: "))

    ROWSNEW = int(input("Enter the number of rows of the new image: "))
    COLSNEW = int(input("Enter the number of columns of the new image: "))

    return ROWS, COLS, ROWSNEW, COLSNEW

In [0]:
# Function: FileName
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the filename along with the path to read and save.
#
#    Parameter:    None
#
#    Result:       returns the name of the file to read and save.
#   
#    Author:       Tanu Nanda Prabhu

def fileName():
 
    filename_to_read = input("Enter the file name to read:  ")
    filename_to_save = input("Enter the file name to save:  ")
    return filename_to_read, filename_to_save

In [0]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName



---



# **Reading a grayscale image in raw format from a file.**

In [27]:
# Initialising rows and column values for the image
ROWS = resolution[0]       
COLS =  resolution[1]       # For example a particular image in this case would contain (256*256) rows and columns meaning 65,536 pixels

# Opening the input image file (RAW format)
fin = open(fileName[0])     # The variable fileName contains the inputted file name to read from  
print(fin)

<_io.TextIOWrapper name='winter-landscape-1600x1000-grayscale.raw' mode='r' encoding='UTF-8'>


Now, we need to construct an 2D array from the raw data (image). A highly efficient way of reading binary data with a know data-type must be used, this can be done with the help of **numpy library**. 

In [28]:
# Loading the input image
print("... Load input image")
img = np.fromfile(fin, dtype = np.uint8, count = ROWS * COLS)
print("Dimension of the old image array: ", img.ndim)
print("Size of the old image array: ", img.size)

... Load input image
Dimension of the old image array:  1
Size of the old image array:  1600000


There is one way that we can convert the 1D array to 2D array such as floor dividing the total number of pixels with rows and columns of the image or columns and columns (either is fine). This can be written with the help of a formula :

`img = tp // (cols, cols)`

**tp** = total pixels; **cols** represents rows and columns of the image. The reason we are using floor divison rather than division because we need to round off the values as a whole number.



In [29]:
# Conversion from 1D to 2D array
img.shape = (img.size // COLS, COLS)
print("New dimension of the array:", img.ndim)
print("----------------------------------------------------")
print(" The 2D array of the original image is: \n", img)
print("----------------------------------------------------")
print("The shape of the original image array is: ", img.shape)

New dimension of the array: 2
----------------------------------------------------
 The 2D array of the original image is: 
 [[240 240 240 ... 230 230 230]
 [240 240 239 ... 230 229 229]
 [240 239 238 ... 231 232 232]
 ...
 [ 50  50  50 ...  50  50  50]
 [ 50  50  50 ...  50  50  50]
 [ 50  50  50 ...  50  50  50]]
----------------------------------------------------
The shape of the original image array is:  (1000, 1600)


In [30]:
# This is an extra step, creating a empty 2D array, with new rows and columns (height and width)
ROWSNEW = resolution[2]  # width
COLSNEW = resolution[3]  # height
imgNew = np.zeros([ROWSNEW, COLSNEW])

# Converting the array into integer
imgNew = imgNew.astype(int)
print("The shape of the new Image array is: ", imgNew.shape)

The shape of the new Image array is:  (400, 640)




---



# **Resizing the image to a specified resolution using single point resampling method**

## **Resampling the image**

In [0]:
# Function: Resampling
#
#   Parameter: img – the original image
#              N – the number of columns
#              M – the number rows
#              x, y – the position for resampling
#
#   Result:    resampled intensity value at (x,y) position

def resampling(img, N, M, x, y):

    i = int(x)   # truncation
    j = int(y)   # truncation
    
    s = (x - i)
    t = (y - j)

    # Displaying the values for inspection
    # With the help of this we can display few points around the center of the image
    # This is mainly used for debugging purpose. (Credits to my professor for providing the code)
    if(x >= (N/2-1) and x <= (N/2+1) and y >=(M/2-1) and y <= (M/2+1)):

       print(x, y, i, j, s, t)
       print("----------------------------------------------------")
       print(img[j][i], img[j][i+1], img[j+1][i], img[j+1][i+1])
       print("----------------------------------------------------")

    
    result = img[j,i] * (1.0-s) * (1.0-t) + img[j,i+1] * s * (1.0-t) + img[j+1,i] * (1.0-s) * t + img[j+1,i+1] * s * t

    # Since we don't want the intensity values in float, we can safely explicitly type cast it to intergers as shown below
    return int(result)



---



## **Resizing the image**

In [0]:
# Function: Image Resizing
#
#   Parameters: img – original image
#               N, M – columns and rows of the original image
#               imgNew – resized the new image
#               N1, M1 – columns and rows of the new image

def resizeImage(img, imgNew, N, M, N1, M1):

    x = 0.0    
    y = 0.0

    Dx = float(N - 1)/(N1 - 1)    # Dx, Dy are the interval lengths for resampling
    Dy = float(M - 1)/(M1 - 1)    # Double data type are not supported in python, so using float is preferable

    for j in range(M1):
        y += Dy
        for i in range(N1):

            # To avoid array index out of bound exception, since the rows and columns of original image is 256 and 256.
            # The resampling methods tries to access the 257 rows and 257 columns and so on...
            # So we need to manually set the thresholds and then break the condition once if the control come here and continue looping
            if(x >= COLS-1 or y >= ROWS-1 ):
                break

            imgNew[j][i] = resampling(img, N, M, x, y) # Calling the resampling function which returns the intensity values at given points
            x = x+Dx

        # If we don't reinitialize the x value to 0.0 then at the end we will get a blank black image. So doing this is compulsory
        x = 0.0
        
    # Printing the newly image array
    print(imgNew)



---



# **Testing the program**

1. Input image filename: “rose.raw”

*   Format: grayscale
*   Original resolution: 256x256
*   New resolution: 500x500



In [4]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName

Enter the number of rows of the old image: 256
Enter the number of columns of the old image: 256
Enter the number of rows of the new image: 500
Enter the number of columns of the new image: 500
Enter the file name to read:  rose.raw
Enter the file name to save:  rose500x500.raw


In [11]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])

127.24448897795635 127.24448897795635 127 127 0.24448897795635105 0.24448897795635105
----------------------------------------------------
133 151 135 140
----------------------------------------------------
127.75551102204453 127.24448897795635 127 127 0.75551102204453 0.24448897795635105
----------------------------------------------------
133 151 135 140
----------------------------------------------------
128.2665330661327 127.24448897795635 128 127 0.2665330661326948 0.24448897795635105
----------------------------------------------------
151 160 140 152
----------------------------------------------------
128.77755511022087 127.24448897795635 128 127 0.7775551102208738 0.24448897795635105
----------------------------------------------------
151 160 140 152
----------------------------------------------------
127.24448897795635 127.75551102204453 127 127 0.24448897795635105 0.75551102204453
----------------------------------------------------
133 151 135 140
----------------------



---



2. Input image filename: “winter-landscape-1600x1000-grayscale.raw”

*  Format: grayscale
*  Original resolution: 1600x1000
*  New resolution: 1000x625




In [15]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName

Enter the number of rows of the old image: 1000
Enter the number of columns of the old image: 1600
Enter the number of rows of the new image: 625
Enter the number of columns of the new image: 1000
Enter the file name to read:  winter-landscape-1600x1000-grayscale.raw
Enter the file name to save:  winter-landscape-1000x525-grayscale.raw


In [22]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])

800.3003003003062 499.5000000000019 800 499 0.30030030030616217 0.5000000000018758
----------------------------------------------------
67 62 67 60
----------------------------------------------------
[[240 238 238 ... 230 230 230]
 [240 238 238 ... 232 233 234]
 [237 237 237 ... 232 232 232]
 ...
 [ 50  50  50 ...  50  49  50]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]




---



3. Input image filename: “winter-landscape-1600x1000-grayscale.raw”

*  Format: grayscale
*  Original resolution: 1600x1000
*  New resolution: 640x400

In [26]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName

Enter the number of rows of the old image: 1000
Enter the number of columns of the old image: 1600
Enter the number of rows of the new image: 400
Enter the number of columns of the new image: 640
Enter the file name to read:  winter-landscape-1600x1000-grayscale.raw
Enter the file name to save:  winter-landscape-640x400-grayscale.raw


In [33]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])

800.751173708922 500.7518796992485 800 500 0.7511737089220105 0.7518796992484909
----------------------------------------------------
67 60 66 56
----------------------------------------------------
[[240 238 238 ... 231 232   0]
 [236 237 239 ... 232 232   0]
 [236 239 235 ... 232 231   0]
 ...
 [ 50  50  49 ...  50  50   0]
 [ 50  50  50 ...  50  50   0]
 [  0   0   0 ...   0   0   0]]




---



# **Saving the new image into a new file in a raw format**

In [34]:
# Save the output image
print("... Save the output image")
imgNew.astype('int8').tofile(fileName[1])
print("... File successfully saved")
# Closing the file
fin.close()

... Save the output image
... File successfully saved




> **Note**: While entering the input. For example if the resolution of an image is **1600x1000**, then it means the **width** is **1600** and the **height** is **1000**. Similarly in the above program the **rows** would be **1000** and the **columns** would be **1600**. 







---

