<a href="https://colab.research.google.com/github/Tanu-N-Prabhu/Image-Processing/blob/master/Assignment_1_(Image_Processing)_Question_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align = "center"><b> CS825-001, Spring/Summer 2020 </b> </h1>

<h3 align = "center"><b>Assignment 1 - Question 1</b></h3>

<h5 align = "center"><b>Assigned Date: Saturday, May 16, 2020</b></h3>

<h5 align = "center"><b> Due Date: Tuesday, May 26, 2020 </b></h3>


# **Question - 1**

### Write a program that reads a grayscale image in raw format from a file; resize the image to a specified resolution using the **single point resampling method**; and save the new image into a new file in raw format. Test your program with the following data

1. Input image filename: “**rose.raw**”
   *   Format: **grayscale**
   *   Original resolution: **256x256**
   *   New resolution: **500x500**


2. Input image filename: “**winter-landscape-1600x1000-grayscale.raw**”

    *  Format: **grayscale**
    *  Original resolution: **1600x1000**
    *  New resolution: **1000x625**


3. Input image filename: “**winter-landscape-1600x1000-grayscale.raw**”

    *  Format: **grayscale**
    *  Original resolution: **1600x1000**
    *  New resolution: **640x400**




---



# **Solution**

# **Input Functions**

Below are some of the functions that take the input from the user such as the resolution (rows, columns) and filename of the image.


### **Importing Libraries**

* The only reason that `numpy` library is used to convert the raw image into **array of pixels**. Mainly used to **store the values in an array**.

* The only reason that `more_itertools` is used because of its `numeric_range` function. A extension of the built-in `range()` function whose arguments can be any orderable numeric type. With only stop specified, start defaults to 0 and step defaults to 1. The output items will match the type of stop. To be more precise, this library helps the for loop to loop around decimal numbers.

In [0]:
# Necessary libraries used for this assignment
import numpy as np

### **Defining all the input functions**

In [0]:
# Function: Resolution
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the number of rows, columns of the old image and the new image.
#
#    Parameter:    None
#
#    Result:       returns the value of the inputted rows and columns of the old and new image.
#   
#    Author:       Tanu Nanda Prabhu

def resolution():

    # Explicitly typed-casted to intergers, because the rows and columns of the images must an integer. 
    ROWS = int(input("Enter the number of rows of the old image: "))
    COLS = int(input("Enter the number of columns of the old image: "))

    ROWSNEW = int(input("Enter the number of rows of the new image: "))
    COLSNEW = int(input("Enter the number of columns of the new image: "))

    return ROWS, COLS, ROWSNEW, COLSNEW

In [0]:
# Function: FileName
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the filename along with the path to read and save.
#
#    Parameter:    None
#
#    Result:       returns the name of the file to read and save.
#   
#    Author:       Tanu Nanda Prabhu

def fileName():
 
    filename_to_read = input("Enter the file name to read:  ")
    filename_to_save = input("Enter the file name to save:  ")
    return filename_to_read, filename_to_save

In [0]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName

Enter the number of rows of the old image: 256
Enter the number of columns of the old image: 256
Enter the number of rows of the new image: 500
Enter the number of columns of the new image: 500
Enter the file name to read:  rose.raw
Enter the file name to save:  rose_500*500_single_point.raw




---



# **Reading a grayscale image in raw format from a file.**

In [0]:
# Initialising rows and column values for the image
ROWS = resolution[0]        # This are hardcoded values for the image resolution
COLS =  resolution[1]       # This particular image would contain (256*256) meaning 65,536 pixels

# Opening the input image file (RAW format)
fin = open(fileName[0])                        # Calling a filename which returns the name of 
print(fin)

<_io.TextIOWrapper name='rose.raw' mode='r' encoding='UTF-8'>


Now we need to construct an 2D array from the raw data (image). A highly efficient way of reading binary data with a know data-type must be used, this can be done with the help of **numpy library**. 

In [0]:
# Loading the input image
print("... Load input image")
img = np.fromfile(fin, dtype = np.uint8, count = ROWS * COLS)
print("Old dimemsion of the array:", img.ndim)
print(img.size)

... Load input image
Old dimemsion of the array: 1
65536


There is one way that we can convert the !D array to 2D array such as floor dividing the total number of pixels with rows and columns of the image or columns and columns (either is fine). This can be written with the help of a formula :

`img = tp // (cols, cols)`

**tp** = total pixels; **rows** and **cols** represents rows and coloumns of the image. The reason we are using floor divison rather than division because we need to round off the values as a whole number.



In [0]:
# Conversion from 1D to 2D array
img.shape = (img.size // COLS, COLS)
print("New dimension of the array:", img.ndim)
print("----------------------------------------------------")
print(" The 2D array of the original image is: \n", img)
print("----------------------------------------------------")
print("The shape of the original image array is: ", img.shape)

New dimension of the array: 2
----------------------------------------------------
 The 2D array of the original image is: 
 [[17 18 18 ... 24 23 23]
 [19 19 18 ... 23 24 23]
 [18 19 19 ... 22 22 21]
 ...
 [ 6  6  6 ...  8  8  7]
 [ 6  6  7 ... 10 10 10]
 [ 8  7  8 ... 17 17 17]]
----------------------------------------------------
The shape of the original image array is:  (256, 256)


In [0]:
# This is an extra step, creating a empty 2D array, with new rows and columns (height and width)


ROWSNEW = resolution[2]
COLSNEW = resolution[3]
imgNew = np.zeros([ROWSNEW, COLSNEW])

# Converting the array into integer
imgNew = imgNew.astype(int)
print("The shape of the new Image array is: ", imgNew.shape)

The shape of the new Image array is:  (500, 500)




---



# **Resizing the image to a specified resolution using single point resampling method**

## **Resampling the image**

In [0]:
# Function: Resampling
#
#   Parameter: img – the original image
#              N – the number of columns
#              M – the number rows
#              x, y – the position for resampling
#
#   Result:    resampled intensity value at (x,y) position

def resampling(img, N, M, x, y):

    i = int(x)   # truncation
    j = int(y)   # truncation
    
    s = (x - i)
    t = (y - j)
    
    result = img[j,i] * (1.0-s) * (1.0-t) + img[j,i+1] * s * (1.0-t) + img[j+1,i] * (1.0-s) * t + img[j+1,i+1] * s * t

    # Since we don't want the intensity values in float, we can safely explicitly type cast it to intergers as shown below
    return int(result)



---



## **Resizing the image**

In [0]:
# Function: Image Resizing
#
#   Parameters: img – original image
#               N, M – columns and rows of the original image
#               imgNew – resized the new image
#               N1, M1 – columns and rows of the new image

def resizeImage(img, imgNew, N, M, N1, M1):

    x = 0.0    
    y = 0.0

    Dx = float(N - 1)/(N1 - 1)    # Dx, Dy are the interval lengths for resampling
    Dy = float(M - 1)/(M1 - 1)    # Double data type are not supported in python, so using float is preferable

    for j in range(M1):
        y += Dy
        for i in range(N1):

            # To avoid array index out of bound exception, since the rows and columns of original image is 256 and 256.
            # The resampling methods tries to access the 257 rows and 257 columns and so on...
            # So we need to manually set the thresholds and then break the condition once if the control come here and continue looping
            if(x >= COLS-1 or y >= ROWS-1 ):
                break

            imgNew[j][i] = resampling(img, N, M, x, y)
            x = x+Dx

        # If we don't reinitialize the x value to 0.0 then at the end we will get a blank black image. So doing this is compulsory
        x = 0.0
        
    # Printing the newly image array
    print(imgNew)

# **Testing the program**

1. Input image filename: “rose.raw”

*   Format: grayscale
*   Original resolution: 256x256
*   New resolution: 500x500



In [0]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])

[[18 18 18 ... 23 23  0]
 [18 18 18 ... 23 23  0]
 [18 18 18 ... 22 22  0]
 ...
 [ 6  6  6 ... 13 13  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


2. Input image filename: “winter-landscape-1600x1000-grayscale.raw”

*  Format: grayscale
*  Original resolution: 1600x1000
*  New resolution: 1000x625




In [0]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])

[[18 18 18 ... 23 23  0]
 [18 18 18 ... 23 23  0]
 [18 18 18 ... 22 22  0]
 ...
 [ 6  6  6 ... 13 13  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


3. Input image filename: “winter-landscape-1600x1000-grayscale.raw”

*  Format: grayscale
*  Original resolution: 1600x1000
*  New resolution: 640x400

In [0]:
resizeImage(img, imgNew, resolution[1], resolution[0], resolution[3], resolution[2])



---



# **Saving the new image into a new file in a raw format**

In [0]:
# Save the output image
print("... Save the output image")
imgNew.astype('int8').tofile(fileName[1])
print("... File successfully saved")
fin.close()

... Save the output image
... File successfully saved




---

