# **CS825-001, Spring/Summer 2020**

## **Assignment 1 - Question 3**

### **Assigned Date: Saturday, May 16, 2020**

### **Due Date: Tuesday, May 28, 2020**


# **Question - 3**

### Write a program that reads “rose.raw” as the input image; change the **intensity quantization level**; and save the new image into a new file in raw format. The original image uses 8 bits per pixel, thus having 256 intensity levels. Test your program by converting intensity level to the following 4 new levels respectivfely

1. 128 levels (by setting the least significant bit of each pixel to 0)
e.g. if a pixel’s original value in binary is 10110101, the new value will be 10110100


2. 64 levels (by setting the two least significant bits of each pixel to 0’s)


3. 32 levels (by setting the three least significant bits of each pixel to 0’s)

4. 16 levels (by setting the four least significant bits of each pixel to 0’s)




---



# **Solution**

# **Input Functions**

Below are some of the functions that take the input from the user such as the resolution (rows, columns) and filename of the image.


### **Importing Libraries**

* The only reason that `numpy` library is used to convert the raw image into **array of pixels**. Mainly used to **store the values in an array**.


In [0]:
# Necessary libraries used for this assignment
import numpy as np

### **Defining all the input functions**

In [0]:
# Function: Resolution
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the number of rows, columns of the input image.
#    Parameter:    None
#
#    Result:       returns the value of the inputted rows and columns of the input image.
#   
#    Author:       Tanu Nanda Prabhu

def resolution():

    # Explicitly typed-casted to intergers, because the rows and columns of the images must an integer. 
    ROWS = int(input("Enter the number of rows of the input image: "))
    COLS = int(input("Enter the number of columns of the input image: "))

    return ROWS, COLS

In [0]:
# Function: FileName
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the filename along with the path to read and save.
#
#    Parameter:    None
#
#    Result:       returns the name of the file to read and save.
#   
#    Author:       Tanu Nanda Prabhu

def fileName():
 
    filename_to_read = input("Enter the file name to read:  ")
    filename_to_save = input("Enter the file name to save:  ")
    return filename_to_read, filename_to_save

In [0]:
# Function: Intensity Level
#
#    Description:  This functions takes the input from the user. 
#                  User should enter the number of intensity levels
#
#    Parameter:    None
#
#    Result:       returns the level of intensity
#   
#    Author:       Tanu Nanda Prabhu

def intensityLevel():
 
    level = int(input("Enter the number of intensity levels: "))

    # 128 - 1 bit to 0
    # 64 - 2 bit to 0
    # 32 - 3 bit to 0
    # 16 - 4 bit to 0
    
    return level

In [0]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName
    level = intensityLevel()     # Calling the intensityLevel() and storing the result in level



---



# **Reading a grayscale image in raw format from a file.**

In [6]:
# Initialising rows and column values for the image
ROWS = resolution[0]       
COLS =  resolution[1]       # For example a particular image in this case would contain (256*256) rows and columns meaning 65,536 pixels

# Opening the input image file (RAW format)
fin = open(fileName[0])     # The variable fileName contains the inputted file name to read from  
print(fin)

<_io.TextIOWrapper name='rose.raw' mode='r' encoding='UTF-8'>


Now, we need to construct an 2D array from the raw data (image). A highly efficient way of reading binary data with a know data-type must be used, this can be done with the help of **numpy library**. 

In [7]:
# Loading the input image
print("... Load input image")
img = np.fromfile(fin, dtype = np.uint8, count = ROWS * COLS)
print("Dimension of the old image array: ", img.ndim)
print("Size of the old image array: ", img.size)
print(img)

... Load input image
Dimension of the old image array:  1
Size of the old image array:  65536
[17 18 18 ... 17 17 17]


## **Conversion of the input image array into binary array**

In [8]:
binArray = np.array([])  # Initializing a new array 'a'
print(binArray.shape)    # The new array has nothing in it

for i in range(len(img)):

# Here each time since we are in loop individual elememts of the input image would be converted to binary, and would be appended to the binArray
    binArray = np.append(binArray, [format(img[i],"08b")])     # This is how we convert an array into binary in python using '08b' (8 bits)

print("The binary converted array is shown below:\n", binArray)

(0,)
The binary converted array is shown below:
 ['00010001' '00010010' '00010010' ... '00010001' '00010001' '00010001']




---



## **Intensity level quantization**
Here we reduce the intensity of the input image into four divverent levels 128, 64, 32 and 16. This can be done by setting the least significant bits to 0. For example in the case of 128 we need to set the least significant bit to 0, similarly for 64 two least significant bit to 0, 32 and 16 three and four least significant bits to 0 respectively.

In [9]:

for i in range(len(binArray)):


# This step is mandatory because if we need to access individual then ond of the best way in python is to convert it to a list.  
    binArrayList = list(binArray[i])


    # Condition for 8 bits in a pixel
    if len(binArrayList) == 8:

        # If the intensity level entered by the user is 128 then set the lsb to 0
        if level == 128:
            binArrayList[7]='0'  # Because 0-7 = 8 bits and the least bit is the 7th bit.
            binArray[i]=''.join(binArrayList)

        # If the intensity level entered by the user is 64 then set the two lsb to 0
        elif level == 64:
            binArrayList[6] = '0'
            binArrayList[7] = '0'
            binArray[i] = ''.join(binArrayList)

        # If the intensity level entered by the user is 32 then set the three lsb to 0
        elif level == 32:
            binArrayList[5] = '0'
            binArrayList[6] = '0'
            binArrayList[7] = '0'
            binArray[i] = ''.join(binArrayList)

        # If the intensity level entered by the user is 16 then set the four lsb to 0
        elif level == 16:
            binArrayList[4] = '0'
            binArrayList[5] = '0'
            binArrayList[6] = '0'
            binArrayList[7] = '0'
            binArray[i] = ''.join(binArrayList)

    else:
        binArray[i]=binArray[i]

print("The updated binary array after intensity quantization will be: \n", binArray)
print("---------------------------------------------------------------------------")
print("The shape of the updated binary array is: \n", binArray.shape)

The updated binary array after intensity quantization will be: 
 ['00010000' '00010000' '00010000' ... '00010000' '00010000' '00010000']
---------------------------------------------------------------------------
The shape of the updated binary array is: 
 (65536,)




---



## **Conversion of the intensity quantized binary array to interger array**

In [10]:
for i in range(len(binArray)):

    binArray[i] = int("".join(str(x) for x in binArray[i]), 2)   # Conversion of updated binary array back to the original integer array

print("The integer quantized array is shown below:\n", binArray)
print("---------------------------------------------------------------------------")
print("The shape of the integer array is: ", binArray.shape)

The integer quantized array is shown below:
 ['16' '16' '16' ... '16' '16' '16']
---------------------------------------------------------------------------
The shape of the integer array is:  (65536,)


There is one way that we can convert the 1D array to 2D array such as floor dividing the total number of pixels with rows and columns of the image or columns and columns (either is fine). This can be written with the help of a formula :

`img = tp // (cols, cols)`

**tp** = total pixels; **cols** represents rows and columns of the image. The reason we are using floor divison rather than division because we need to round off the values as a whole number.



In [0]:
intArray = binArray

In [12]:
# Conversion from 1D to 2D array
intArray.shape = (intArray.size // COLS, COLS)
print("New dimension of the array:", intArray.ndim)
print("----------------------------------------------------")
print("The shape of the original image array is: ", intArray.shape)
img = intArray.astype(int)   # Explicit type casting to integer, just in case.
print(" The 2D array of the original image is: \n", img)

New dimension of the array: 2
----------------------------------------------------
The shape of the original image array is:  (256, 256)
 The 2D array of the original image is: 
 [[16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 16 16 16]]




---



# **Testing the program**

1. 128 levels (by setting the least significant bit of each pixel to 0)
e.g. if a pixel’s original value in binary is 10110101, the new value will be 10110100.

In [5]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName
    level = intensityLevel()     # Calling the intensityLevel() and storing the result in level

Enter the number of rows of the input image: 256
Enter the number of columns of the input image: 256
Enter the file name to read:  rose.raw
Enter the file name to save:  rose128.raw
Enter the number of intensity levels: 128


In [16]:
print(" The 2D array of the original image is: \n", img)

 The 2D array of the original image is: 
 [[16 18 18 ... 24 22 22]
 [18 18 18 ... 22 24 22]
 [18 18 18 ... 22 22 20]
 ...
 [ 6  6  6 ...  8  8  6]
 [ 6  6  6 ... 10 10 10]
 [ 8  6  8 ... 16 16 16]]




---



2. 64 levels (by setting the two least significant bits of each pixel to 0’s)

In [11]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName
    level = intensityLevel()     # Calling the intensityLevel() and storing the result in level

Enter the number of rows of the input image: 256
Enter the number of columns of the input image: 256
Enter the file name to read:  rose.raw
Enter the file name to save:  rose64.raw
Enter the number of intensity levels: 64


In [19]:
print(" The 2D array of the original image is: \n", img)

 The 2D array of the original image is: 
 [[16 16 16 ... 24 20 20]
 [16 16 16 ... 20 24 20]
 [16 16 16 ... 20 20 20]
 ...
 [ 4  4  4 ...  8  8  4]
 [ 4  4  4 ...  8  8  8]
 [ 8  4  8 ... 16 16 16]]




---



3. 32 levels (by setting the three least significant bits of each pixel to 0’s)



In [5]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName
    level = intensityLevel()     # Calling the intensityLevel() and storing the result in level

Enter the number of rows of the input image: 256
Enter the number of columns of the input image: 256
Enter the file name to read:  rose.raw
Enter the file name to save:  rose32.raw
Enter the number of intensity levels: 32


In [13]:
print(" The 2D array of the original image is: \n", img)

 The 2D array of the original image is: 
 [[16 16 16 ... 24 16 16]
 [16 16 16 ... 16 24 16]
 [16 16 16 ... 16 16 16]
 ...
 [ 0  0  0 ...  8  8  0]
 [ 0  0  0 ...  8  8  8]
 [ 8  0  8 ... 16 16 16]]




---



4. 16 levels (by setting the four least significant bits of each pixel to 0’s)

In [5]:
# Function: main
#
#    Description:  This is the main function of the program
#                  On executing this function, all the functions declared inside will be called. Just like in C, C++, etc.
#
#    Parameter:    None
#
#    Result:       Calls every function declared inside it.
#   
#    Author:       Tanu Nanda Prabhu

if __name__ == "__main__":

    resolution = resolution()    # Calling the resolution() and storing the result in resolution
    fileName = fileName()        # Calling the fileName() and storing the result in fileName
    level = intensityLevel()     # Calling the intensityLevel() and storing the result in level

Enter the number of rows of the input image: 256
Enter the number of columns of the input image: 256
Enter the file name to read:  rose.raw
Enter the file name to save:  rose16.raw
Enter the number of intensity levels: 16


In [13]:
print(" The 2D array of the original image is: \n", img)

 The 2D array of the original image is: 
 [[16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 16 16 16]]




---



# **Saving the new image into a new file in a raw format**

In [15]:
# Save the output image
print("... Save the output image")
img.astype('int8').tofile(fileName[1])
print("... File successfully saved")
# Closing the file
fin.close()

... Save the output image
... File successfully saved




> **Note**: While entering the input. For example if the resolution of an image is **1600x1000**, then it means the **width** is **1600** and the **height** is **1000**. Similarly in the above program the **rows** would be **1000** and the **columns** would be **1600**. 





---

